<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_694a9d25909d8',
    'title' => __('Service Information Settings', 'modularity-service-info'),
    'fields' => array(
        0 => array(
            'key' => 'field_694a9d267cd58',
            'label' => __('Slug', 'modularity-service-info'),
            'name' => 'slug',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The slug you want for the singular posts, defaults to service-information. Don\'t forget to flush your permalink rules after changing.', 'modularity-service-info'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => __('service-information', 'modularity-service-info'),
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_694a9e4303cda',
            'label' => __('Service information page', 'modularity-service-info'),
            'name' => 'service_information_page',
            'aria-label' => '',
            'type' => 'post_object',
            'instructions' => __('The page where you present service information', 'modularity-service-info'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'page',
            ),
            'post_status' => array(
                0 => 'publish',
            ),
            'taxonomy' => '',
            'return_format' => 'id',
            'multiple' => 0,
            'save_custom' => 0,
            'save_post_status' => 'publish',
            'acfe_bidirectional' => array(
                'acfe_bidirectional_enabled' => '0',
            ),
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'bidirectional' => 0,
            'ui' => 1,
            'bidirectional_target' => array(
            ),
            'save_post_type' => '',
        ),
        2 => array(
            'key' => 'field_6953e2f70b4e1',
            'label' => __('LiteSpeed ESI cache support', 'modularity-service-info'),
            'name' => 'litespeed_esi_cache_support',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Try to add support for updating the badge even though the page is cached with LiteSpeed. This will use LiteSpeed ESI to properly update only the badge part of the page.', 'modularity-service-info'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        3 => array(
            'key' => 'field_69a4556aa8c49',
            'label' => __('Schedule unpublish task', 'modularity-service-info'),
            'name' => 'schedule_unpublish_task',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('This schedule a cron job that runs via WP Cron and unpublishes old service information. It can also be triggered by WP CLI using the cron commands. If no job is scheduled you will have to delete the information manually or use the WP CLI command "service-info unpublish" to unpublish old information.', 'modularity-service-info'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '-' => __('No', 'modularity-service-info'),
                'hourly' => __('Hourly', 'modularity-service-info'),
                'daily' => __('Daily', 'modularity-service-info'),
            ),
            'default_value' => __('-', 'modularity-service-info'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
        4 => array(
            'key' => 'field_69a456f36ccd5',
            'label' => __('Schedule import of external information sources', 'modularity-service-info'),
            'name' => 'schedule_import_external_info',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('A cron job can be scheduled to import information from external sources. This will be run by WP Cron or by manually running the event "modularity_service_info_import". If not scheduled, you can use the WP CLI command "service-info import" to import external sources via for instance crontab.', 'modularity-service-info'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '-' => __('No', 'modularity-service-info'),
                'hourly' => __('Hourly', 'modularity-service-info'),
                'daily' => __('Daily', 'modularity-service-info'),
            ),
            'default_value' => __('-', 'modularity-service-info'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'create_options' => 0,
            'save_options' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'service-information-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));
}